name: DailyRewards
version: ${project.version}

authors: [Revivalo, ChimpGamer, Verschuls]
description: Reward system for players
website: https://discord.athelion.eu/

main: eu.athelion.dailyrewards.DailyRewardsPlugin
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Oraxen
  - ItemsAdder

commands:
  reward:
    aliases: [rw]
  rewards:
    aliases: [rws]
  dailyreward:
    aliases: [ dreward ]
  dailyrewards:
    aliases: [ drewards ]
